--vim.g["VM_default_mappings"] = -1
--print(vim.g["VM_default_mappings"])
--vim.g["VM_maps"] = {}
--vim.g["VM_default_mappings"] = 0

--return {
--  config = function()
--    vim.g.VM_maps = {}
    -- Note: <Plug> refers to a function that you can "plug" in the hotkey on the left side.
    --       VM-Find-Under is a function specific to Vim Multi-line plugin.
--    vim.keymap.set("n", "<C-x>", "<Plug>(VM-Add-Cursor-At-Pos)")
  --  "mg979/vim-visual-multi", 
  --  config = function() 
  --    vim.keymap.set("n", "<C-x>", "<Plug>(VM-Find-Under)")
  --    vim.keymap.set("n", "<C-x>", "<Plug>(VM-Find-Under)")
--  end
--}
